package edu.kvcc.cis298.inclass3.inclass3;

import android.app.Activity;
import android.net.Uri;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;  //  CHANGED WHICH SUPPORT WE MADE THE FRAGMENT FROM
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;




public class CrimeFragment extends Fragment {

    //Declae a class level variable
    private Crime mCrime;


    //This method does not do the inflating of the view
    //like the onCreate for an activity does.
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        // Create a new instance of a cro,e
        mCrime = new Crime();
    }

 //   @Nullable  generated by right click generate/ Override metthod

    //This metod IS responsible for inflating the view
    //and getting the content on the screen.
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View v= inflater.inflate(R.layout.fragment_crime, container, false);    // WE ADDED THIS CODE to inflate a FRAGMENT to create the view
        return  v;
    }
}
